services:
  mysql:
    image: mysql:8.0
    container_name: estapar-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking
      MYSQL_USER: parking
      MYSQL_PASSWORD: parking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uparking", "-pparking"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
